language: php

php:
  - 5.5
  - 5.6

env:
  - NETTE=default
  - NETTE=nette-2.1
  - NETTE=nette-2.2

install:
  - php ./tests/prepare-composer.php
  - composer self-update || echo "failed :("
  - time composer install --no-interaction --prefer-source --optimize-autoloader

before_script:
  - ./vendor/bin/tester -c ./tests/php.ini-unix --info
  - time ./vendor/bin/parallel-lint -e php,phpt --exclude vendor .

script:
  - ./vendor/bin/tester -s -j 32 -c ./tests/php.ini-unix ./tests/

after_failure:
  - 'for i in $(find ./log -name \*.log); do echo "--- $i"; cat $i; echo; echo; done'
  - 'for i in $(find ./tests -name \*.log); do echo "--- $i"; cat $i; echo; echo; done'
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'

notifications:
  slack: damejidlo:6fIQkFK0GljdHAyTLVtz5dip
  email: false
